### ISSUE TITLE
Formulas are saved in settings but do not work really.

### ISSUE THREAD

**Issue by Giannatosp** [caewok/fvtt-action-initiative#3]
You can enter a formula in each field in the module settings, but when it is selected in the normal initiative dialogue, it just rolls the original default formula. Even in the "bonus" and "other" options, this is the same where it SHOWS the correct formula you have entered in settings! If this helps: in the other and bonus options, if you input manually the formula EVERY round, it rolls it correctly.

**Comment by caewok** [comment]
Yes, the "bonus" and "other" options were pulling from the default formula instead of the formula entered in the settings. Fixed in v0.1.1. 

As for other formulas in the settings, I did some testing and it looks like entering formulas in the settings results in those formulas being used in the corresponding roll. But if you are not seeing that, please open a new issue with additional details on when that is not working. 

Some things to keep in mind:
- In settings, you have to hit the "save" button in the Advanced Configuration pop-up after adding the formulas. This can be easy to forget, as the save button sometimes is hidden so you have to scroll down.
- For Weapons formulas, the description was mislabeled. The Weapons formulas are used with the "Weapon Type" variant. The "Weapon Damage" variant just pulls the weapon damage dice formula directly from each weapon. I fixed the labeling in v0.1.1.
